name: Databricks Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  list-files-on-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
    - name: AZ Login with SPN
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS_2 }}'
    
    - name: Generate Access Token
      id: access_token
      run: |
        access_token=$(az account get-access-token --resource=${{ secrets.RESOURCE_ID }} --query 'accessToken' -o tsv)
        
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
      
    - name: List files in Current Working Directory
      run: |
        cat > ./test_13.py << EOF
        This is a test fileA
        EOF
        ls 
        pwd

    - name: Databricks Integration & API Usage
      run: |
        export DATABRICKS_HOST=${{ secrets.DBX_H }}
        export DATABRICKS_TOKEN=$(az account get-access-token --resource=${{ secrets.RESOURCE_ID }} --query 'accessToken' -o tsv)
        databricks fs ls dbfs:/tmp/
        #databricks fs cp --recursive ./test_13.py dbfs:/tmp/
        #databricks workspace import_dir ./steps /Users/suresrah@lab.morganstanley.com/rahul_test_2/check_out/
        databricks fs cp ./config  --recursive dbfs:/tmp/
        databricks jobs run-now --job-id 460384054734043

    
