name: Databricks Workflow

on:
  push:
    branches:
      - main

jobs:
  list-files-on-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS_2 }}'
    
    - name: Generate Access Token
      id: access_token
      run: |
        access_token=$(az account get-access-token --resource=${{ secrets.RESOURCE_ID }} --query 'accessToken' -o tsv)
        

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
        
    - name: List files in cwd
      run: |
        cat > ./test_11.py << EOF
        This is a test fileA
        EOF
        ls 
        pwd

    - name: List Files on DBFS
      env:
          DATABRICKS_HOST: ${{ secrets.DBX_H }}
          DATABRICKS_TOKEN: ${{ DBX_AT_TEMP4 }}
      run: |
        databricks fs ls dbfs:/tmp/
        databricks fs cp --recursive ./test_11.py dbfs:/tmp/
    
