
name: Databricks Workflow

on:
  push:
    branches:
      - main

jobs:
  list-files-on-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Authenticate and get access token
      id: login
      uses: azure/login@v1
      with:
          creds: '{"clientId":"${{ secrets.SPN_CLI }}","clientSecret":"${{ secrets.CLIS }}","subscriptionId":"${{ secrets.SUB }}","tenantId":"${{ secrets.TENA_I }}"}'
          allow-no-subscriptions: true
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
    - name: List files in cwd
      run: |
        cat > ./test1.py << EOF
        This is a test file
        EOF
        ls 
        pwd
    - name: List Files on DBFS
      env:
          DATABRICKS_HOST: ${{ secrets.DBX_H }}
          DATABRICKS_TOKEN: ${{ steps.login.outputs.ACCESS_TOKEN }}
      run: |
        databricks fs ls dbfs:/tmp/
        databricks fs cp --recursive ./test1.py dbfs:/tmp/
        
        
        
        
    
